# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFDerHcOY3yMdiORT4LHpTwCSsRv-bdI
"""

name =input("نام شما چیست؟")
while not name:
    name=input("لطفا نام قشنگت رو بگو!")
if name:
  print("امروز زیبا شدی",name)

print()
print("لطفا فقط عدد 1 یا 2 انتخاب کنید")
topic=input("انتخاب شما:")
print()

project_score = 0
py_score = 0

if topic=="1":
    personality1=input("""وقتی یک کار بزرگ داری
1:ترجیح میدی برنامه ریزی کنی
2:مستقیم شروع کنی و جلو بری""")
    while personality1 not in["1","2"]:
         print("لطفا عدد یک و دو انتخاب کن.")
         personality1=input("انتخاب شما:")


    print()

    personality2=input(""" وقتی یک پروژه طولانی میشود کدام را ترجیح میدی؟
    1:بدون برنامه مشخص جلو میرم
    2:کار را مرحله به مرحله و منظم جلو میبرم""")
    while personality2 not in["1","2"]:
         print("لطفا عدد یک و دو انتخاب کن.")
         personality2=input("انتخاب شما:")

    print()

    personality3=input("""وقتی با مشکل غیر منتظره در پروژه روبرو میشی کدام را انتخاب میکنی؟
    1:خودم راه حل های مختلف را بررسی و بهترین را انتخاب میکنم
    2:از دیگران کمک میگیرم""")
    while personality3 not in["1","2"]:
         print("لطفا عدد یک و دو انتخاب کن.")
         personality3=input("انتخاب شما:")

    if personality1=="1":
        project_score+= 2
    elif personality1=="2":
        project_score+= 1

    if personality2=="1":
        project_score+= 2
    elif personality2=="2":
        project_score+=1

    if personality3=="1":
        project_score+= 2
    elif personality3=="2":
        project_score+=1

elif topic=="2":
    py1=input("""وقتی با یک همکار اختلاف نظر پیدا میکنی کدام را ترجیح میدی؟
    1:با ارامش صحبت میکنم تا مشکل را حل کنیم
    2:کمی فاصله میگیرم و بعدا درباره مشکل صحبت میکنم""")
    while py1 not in["1","2"]:
         print("لطفا عدد یک و دو انتخاب کن.")
         py1=input("انتخاب شما:")

    print()

    py2=input("""وقتی یکی از اعضای تیم ناراحت یا بی انگیزه است کدام را ترجیح میدی؟
    1:با او صحبت میکنم و سعی میکنم دلیلش را بفهمم
    2:ترجیح میدم روی کار خودم تمرکز کنم""")
    while py2 not in["1","2"]:
         print("لطفا عدد یک و دو انتخاب کن.")
         py2=input("انتخاب شما:")
    print()

    py3=input("""وقتی باید ببین چند نفر برای انجام کار هماهنگی ایجاد کنی کدام را ترجیح میدی؟
    1:هماهنگی و تقسیم کار را بین افراد انجام میدهم
    2:ترجیح میدهم هرکس خودش وظیفه اش را انجام بدهد""")
    while py3 not in["1","2"]:
         print("لطفا عدد یک و دو انتخاب کن.")
         py3=input("انتخاب شما:")

    print()

    if py1=="1":
       py_score+=2
    elif py1=="2":
       py_score+=1


    if py2=="1":
       py_score+=2
    elif py2=="2":
       py_score+=1


    if py3=="1":
       py_score+=2
    elif py3=="2":
       py_score+=1


project_percent = (project_score/6)*100
py_percent = (py_score/6)*100

print("تناسب شما با مدیریت پروژه:", project_percent, "%")
print("تناسب شما با مدیریت منابع انسانی :", py_percent, "%")

if project_percent > py_percent:
   print("شخصیت شما بیشتر به مدیریت پروژه میخورد")

elif py_percent > project_percent:
   print("شخصیت شما بیشتر به مدیریت منابع انسانی میخورد")

else:
   print("شخصیت شما به هردو حوزه به یک اندازه نزدیک است")

